# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.0.4.dev503+g94ada3d.d20221011'
__version_tuple__ = version_tuple = (3, 0, 4, 'dev503', 'g94ada3d.d20221011')
